INSERT INTO state_tbl (state_id, state_name)
VALUES(1, 'Alabama'),
      (2, 'Alaska'),
      (3, 'Arizona'),
      (4, 'Arkansas'),
      (5, 'California'),
      (6, 'Colorado'),
      (7, 'Connecticut'),
      (8, 'Delaware'),
      (9, 'Florida'),
      (10, 'Georgia'),
      (11, 'Hawaii'),
      (12, 'Idaho'),
      (13, 'Illinios'),
      (14, 'Indiana'),
      (15, 'Iowa'),
      (16, 'Kansas'),
      (17, 'Kentucky'),
      (18, 'Louisiana'),
      (19, 'Maine'),
      (20, 'Maryland'),
      (21, 'Massachusetts'),
      (22, 'Michigan'),
      (23, 'Minnesota'),
      (24, 'Missippi'),
      (25, 'Missouri'),
      (26, 'Montana'),
      (27, 'Nebraska'),
      (28, 'Nevada'),
      (29, 'New Hampshire'),
      (30, 'New Jersey'),
      (31, 'New Mexico'),
      (32, 'New York'),
      (33, 'North Carolina'),
      (34, 'North Dakota'),
      (35, 'Ohio'),
      (36, 'Oklahoma'),
      (37, 'Oregon'),
      (38, 'Pennslvania'),
      (39, 'Rhode Island'),
      (40, 'South Carolina'),
      (41, 'Tennessee'),
      (42, 'Texas'),
      (43, 'Utah'),
      (44, 'Vermont'),
      (45, 'Virginia'),
      (46, 'Washington'),
      (47, 'West Virginia'),
      (48, 'Wisconsin'),
      (49, 'Wyoming'),
      (50, 'South Dakota');
